services:
  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    container_name: neurosprints_api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Telegram__BotToken: ${Telegram__BotToken}
      TokenSettings__Audience: ${TokenSettings__Audience}
      YandexObjectStorage__AccessKey: ${YandexObjectStorage__AccessKey}
      YandexObjectStorage__SecretKey: ${YandexObjectStorage__SecretKey}
      YDB__SaFilePath: /app/neurosprints-developer.sa
      YDB__Host: ${YDB__Host}
      YDB__Port: ${YDB__Port}
      YDB__Database: ${YDB__Database}

    ports:
      - "80:8080"
    volumes:                                                                                                            
      - ./neurosprints-developer.sa:/app/neurosprints-developer.sa:ro