name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Yandex Container Registry
        run: |
          echo "${{ secrets.YCR_TOKEN }}" | docker login cr.yandex \
            --username oauth \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build -t cr.yandex/${{ secrets.YCR_REPO_ID }}/backend-neurointegration-sprints:latest -f src/Api/Dockerfile .

      - name: Push Docker image
        run: |
          docker push cr.yandex/${{ secrets.YCR_REPO_ID }}/backend-neurointegration-sprints:latest
